// Animal Endpoints

# Retrieve all animals
GET http://localhost:7070/api/v1/animals

###

# Retrieve an animal by ID
GET http://localhost:7070/api/v1/animals/7

###

# Create a new animal
POST http://localhost:7070/api/v1/animals/zoo/4
Content-Type: application/json

{
  "animalName": "Lion386y7824",
  "animalAge": 4,
  "speciesId": 1
}

###

# Update an existing animal
PUT http://localhost:7070/api/v1/animals/11
Content-Type: application/json

{
  "animalName": "Ib",
  "animalAge": 5
}

###

# Delete an animal by ID
DELETE http://localhost:7070/api/v1/animals/11

###

# Retrieve the zoo associated with a specific animal
GET http://localhost:7070/api/v1/animals/10/zoo
